# Generated by Django 5.0.6 on 2024-07-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('long_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='photo/products')),
                ('image1', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image2', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image3', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image4', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image5', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image6', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image7', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('image8', models.ImageField(default='img.jpg', upload_to='photo/products')),
                ('stock', models.IntegerField()),
                ('brand', models.BooleanField(default=True)),
                ('number_sells', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categories.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
