# Generated by Django 5.0.6 on 2024-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image7',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image8',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
