# Generated by Django 5.0.6 on 2024-07-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
